name: windows-build

on:
  workflow_dispatch:
  push:
    paths:
    - merge_subdomains/**
    - misclassification/**
    - segmentation/**
    - build.ps1
    - .github/workflows/build-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: |
          .\build.ps1
