name: ubuntu-build

on:
  workflow_dispatch:
  push:
    paths:
    - merge_subdomains/**
    - misclassification/**
    - segmentation/**
    - build.sh
    - .github/workflows/build-ubuntu.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: dependencies
        run: |
          sudo apt update
          sudo apt-get install -y build-essential
          sudo apt-get install -y mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxi-dev libxcursor-dev
      - name: build
        env:
          CC: gcc
          CXX: g++
        run: |
          gcc --version
          ./build.sh
